-- migrate:up
CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  kakao_id BIGINT(20) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  nickname VARCHAR(20) NOT NULL,
  profile_image VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);

-- migrate:down
DROP TABLE users;
